core/urls.py
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('registrees', views.register, name='register'),
    path('investments', views.investments, name='investments'),
    path('s', views.reg_success, name='reg_success'),
    path('member/<slug:member_number>/', views.member, name='member'),

]

shcomrade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from datetime import date
from django.db.models import F, Q

# Create your models here.
class Registration(models.Model):
    first_name = models.CharField(max_length=15)
    second_name = models.CharField(max_length=15)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone_number = models.IntegerField()

    def __str__(self):
        return self.first_name


class Member(models.Model):
    registration = models.OneToOneField(Registration, on_delete=models.PROTECT)
    member_number = models.CharField(max_length=8)
    member_password = models.CharField(max_length=8)
    joined_on = models.DateField(auto_now=True)

    def __str__(self):
        return self.member_number
    
    def del_obj(self):
        obj = Registration.objects.get(id=self.registration_id)
        obj.delete()


class Transaction(models.Model):
    types = (
        ('CTB', 'Contribution'),
        ('RPT', 'Repayment'),
        ('INV', 'Investment')
    )

    member = models.ForeignKey(Member, on_delete=models.PROTECT)
    transaction_type = models.CharField(max_length=3, choices=types)
    amount = models.PositiveIntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.transaction_type} on {self.date}'


class Investment(models.Model):
    principal = models.OneToOneField(Transaction, on_delete=models.PROTECT)
    investment_name = models.CharField(max_length=20)
    investment_rate = models.FloatField()

    def __str__(self):
        return self.investment_name
    
    

class Leaver(models.Model):
    member = models.ForeignKey(Member, on_delete=models.PROTECT)
    notice_given = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.member} notice given on {self.notice_given}'

core/forms.py
from django import forms
from .models import Registration
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit


class Login(forms.Form):
    member_number = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'p-2 rounded-md mx-auto'}))

    class Meta:
        widgets = {
            'member_number': forms.TextInput(attrs={'class': 'p-2 bg-slate-400 rounded-md mx-auto', 'placeholder': 'John'}),
        }

    def clean_all(self):
        member_no = self.cleaned_data['member_number']
        # validate age
        return member_no

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            'member_number',
            'password',
            Submit('submit', 'Submit', css_class='bg-black rounded-md border text-white border-black px-5 text-end py-2 my-2 hover:bg-white hover:text-black')
        )


class Transaction(forms.Form):
    member_number = forms.CharField()
    phone_number = forms.CharField()
    amount = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'p-2 rounded-md mx-auto', 'min': 1000}))

    class Meta:
        widgets = {
            'member_number': forms.TextInput(attrs={'class': 'p-2 bg-slate-400 rounded-md mx-auto', 'placeholder': 'John'}),
            'phone_number': forms.NumberInput(attrs={'class': 'p-2 bg-slate-400 rounded-md mx-auto', 'placeholder':'254700000000', 'min': '254100000000'})
        ,}

    def clean_all(self):
        phone_no = self.cleaned_data['phone_number']
        # validate age
        return phone_no

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            'member_number',
            'phone_number',
            'amount',
            Submit('submit', 'Submit', css_class='bg-black rounded-md border text-white border-black px-5 text-end py-2 my-2 hover:bg-white hover:text-black')
        )


class Leaver(forms.Form):
    member_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'p-2 rounded-md mx-auto'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'p-2 rounded-md mx-auto'}))

    def clean_all(self):
        password = self.cleaned_data['password']
        # validate age
        return password

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            'member_number'
            'password',
            Submit('submit', 'Submit', css_class='bg-black rounded-md border text-white border-black px-5 text-end py-2 my-2 hover:bg-white hover:text-black')
        )


class Register(forms.ModelForm):
    
    class Meta:
        model = Registration
        fields = ('first_name', 'second_name', 'date_of_birth', 'email', 'phone_number')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'p-2 rounded-md mx-auto', 'placeholder': 'John'}),
            'second_name': forms.TextInput(attrs={'class': 'p-2 rounded-md mx-auto', 'placeholder': 'Doe'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'p-2 rounded-md  mx-auto'}),
            'email': forms.EmailInput(attrs={'class': 'p-2 rounded-md  mx-auto', 'placeholder': 'johndoe@gmail.com'}),
            'phone_number': forms.NumberInput(attrs={})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            'first_name',
            'second_name',
            'date_of_birth', 
            'email', 
            'phone_number',
            Submit('submit', 'Submit', css_class='bg-black rounded-md border text-white border-black px-5 text-end py-2 my-2 hover:bg-white hover:text-black')
        )

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from urllib3 import HTTPResponse
from .models import Registration, Investment, Member, Transaction, Leaver
from .forms import Register, Login, Leaver
from calendar import monthrange
from datetime import date, timedelta
from django_daraja.mpesa.core import MpesaClient
import math

def monthdelta(d1, d2):
    delta = 0
    while True:
        mdays = monthrange(d1.year, d1.month)[1]
        d1 += timedelta(days=mdays)
        if d1 <= d2:
            delta += 1
        else:
            break
    return delta

# Create your views here.
def index(request):

    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            member_no = form.cleaned_data['member_number']
            password = form.cleaned_data['password']
            member = Member.objects.get(member_number=member_no)

            if password == member.member_password:
                return redirect('member/'+ member_no)

    form = Login()
    context = {'form': form}
    return render(request, 'index.html', context)

def register(request):
    pending_approval = Registration.objects.all()
    members = Member.objects.all()
    context = {"person": pending_approval, "members": members}
    return render(request, 'pending_report.html', context)

def investments(request):
    invest = Investment.objects.all()
    context = {"invest": invest}
    return render(request, "investments.html", context)

def reg_success(request):
    return render(request, 'reg-success.html')


def member(request, member_number):
    member = get_object_or_404(Member, member_number=member_number)
    contributions = Transaction.objects.filter(transaction_type='CTB')
    my_contribs = Transaction.objects.filter(member=member,transaction_type='CTB')
    repayments = Transaction.objects.filter(transaction_type='RPT')
    investments = Investment.objects.all()

    arrears = 1000
    months_spent = monthdelta(member.joined_on, date.today())
    i = months_spent
    while i > 0:
        if months_spent < 3:
            arrears += 500
        else:
            arrears += 1000
        i -= 1

    def calculate(iterable):
        total = 0
        for contribution in iterable:
            total = contribution.amount + total
        return total
    
    total_made = 0
    for investment in investments:
        m =  monthdelta(investment.principal.date, date.today())
        total_made = investment.principal.amount + investment.principal.amount * investment.investment_rate * m

    total = calculate(contributions)
    mine = calculate(my_contribs)
    if repayments:
        repayments = calculate(repayments)
    else:
        repayments = 0 
    arrears -= mine

    if arrears < 0:
        arrears = f"0 | {arrears*-1} overpaid"

    revenue = total + total_made - repayments
    shares = math.floor((mine/total) * revenue)

    context = {"member": member, "contrib": total, "returns": total_made, "mine": mine, "arrears": arrears, "revenue": revenue, "shares":shares}
    return render(request, "member_dash.html", context)


def leaving(request):
    if request.method == 'POST':
        form = Leaver(request.POST)
        if form.is_valid():
            member_no = form.cleaned_data['member_number']
            password = form.cleaned_data['password']
            member = Member.objects.get(member_number=member_no)

            if password == member.member_password:
                return redirect('leaver/'+ member_no)
            else:
                return HTTPResponse('INVALID PASSWORD -- cannot be allowed to leave at this time')

    form = Leaver()
    context = {'form': form}
    return render(request, 'index.html', context)

"""
def transaction(request):
    cl = MpesaClient()
    phone_number = '0700111222'
    amount = 1
    account_reference = 'reference'
    transaction_desc = 'Description'
    callback_url = request.build_absolute_uri(reverse('mpesa_stk_push_callback'))
    response = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
    return HTTPResponse(response)
"""

core/templates/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up - Shcomrade Chama.</title>
    <!--Bootstrap Library Links-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"  integrity="sha384ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--FontAwesome CDN Link-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="fontawesome-free-5.15.3-web/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="fontawesome-free-5.15.3-web/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="fontawesome-free-5.15.3-web/css/fontawesome.css">
    <!--CSS File-->
    <link rel="stylesheet" type="text/css" href="{% static 'dist/style.css'%}">
    <link rel="stylesheet" href="{% static 'dist/output.css' %}">
    <link rel="icon" href="" type="image/png">
</head>
<body class="bg-no-repeat bg-cover h-[100vh]">
        <div class="flex flex-row justify-center align-middle">
            <div class="hidden md:flex md:flex-col bg-gradient-to-r from-[rgb(116,62,227)] to-[rgba(246,110,26,1)] md:justify-center md:w-[100%] md:rounded md:rounded-r-lg md:items-center md:h-[100vh]">
                <div>
                    <div class="font-['Poppins'] text-white text-center">
                        <h2 class="text-6xl font-extrabold max-w-prose">Shcomrade<br>Chama</h2>
                        <p class="text-sm font-medium">Digital Chama System</p>
                    </div>
                </div>
            </div> <!--Left Half-->
            <div class="flex flex-col w-[100%] items-center justify-center">
                    <div class="font-['Poppins']">
                        <h2 class="text-3xl text-white p-5 font-extrabold">Hello Again</h2>
                        <form method="post" class="login text-indigo-300">
                            {% crispy form form.helper %}
                        </form>
                    </div>
                    <div class="form-field">
                        <p>Are you new here? <a href="signup.html">Sign Up</a></p>
                    </div>
                </div>
                    
                
            </div> <!--Right Half-->
        </div>
    
    
</body>
</html>

core/templates/investments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/dist/output.css">
</head>
<body>
    <h1 class="text-4xl text-center">INVESTMENTS</h1>
    {% if invest %}
        {% for investment in invest %}
            <p>{{ investment.investment_name }}</p>
            <p>{{ investment.invested_on}}</p>
            <p>{{ investment.amount_invested}}</p>
            <p>{{ investment.investment_rate }}</p>
        {% endfor %}
    {% else %}
            <p>FRANK!</p>
    {% endif %}
</body>
</html>

core/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/dist/output.css">
    <link rel="stylesheet" href="../static/dist/extra.css">
</head>
<body class="h-[100vh]">
    <div class="flex my-auto h-[100vh]">
        <div class="mx-auto h-[100vh] leaves">
            <h1 class="text-5xl text-center font-sans font-bold py-36 pb-2 text-purple-900 mx-auto">Shcomrade Database Management System</h1>
            <div class="text-white font-bold text-center mt-2 px-5 py-3 rounded-md mx-52 bg-blue-700 hover:bg-blue-500">
                <h3>Learn More</h3>
            </div>
        </div>
        <div class="login mb-auto bg-gradient-to-r from-rose-600 to-fuchsia-600 px-14 my-auto h-[100vh]">
            <form action="" class="pt-8">
                <h2 class="font-sans font-bold text-3xl text-white my-3">Sign Up</h2>
                <div class="names flex space-x-2">
                    <div class="py-1">
                        <label for="first-name" class="text-white">First Name</label><br>
                        <input type="text" name="first-name" class="p-2 rounded-md mx-auto" placeholder="John" required>
                    </div>
                    <div class="py-1">
                        <label for="last-name" class="text-white">Last Name</label><br>
                        <input type="text" name="last-name" class="p-2 rounded-md  mx-auto" placeholder="Doe" required>
                    </div>
                </div>
                <div class="py-1">
                    <label for="dob" class="text-white">Date of Birth</label><br>
                    <input type="date" name="dob" class="p-2 rounded-md  mx-auto" required>
                </div>
                <div class="py-1">
                    <label for="first-name" class="text-white">Email</label><br>
                    <input type="email" name="first-name" class="p-2 rounded-md mx-auto" placeholder="doejohn@uranus.com" required>
                </div>
                <div class="py-1">
                    <label for="first-name" class="text-white">Phone Number</label><br>
                    <span class="p-2 bg-slate-300 border rounded-l-md">+254</span><input type="text" name="first-name" class="p-2 rounded-r-md" placeholder="7XXXXXXXX" required>
                </div>
                <button class="bg-black transpa rounded-md border text-white border-black px-5 text-end py-2 my-2 hover:bg-white hover:text-black">Submit</button>
            </form>
            <div class="absolute bottom-0">
                <p>Copyright &copy; 2023 Shcomrade Chama Ltd.</p>
            </div>
        </div>
    </div>
</body>
</html>

core/templates/member_dash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Dashboard</title>
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'dist/dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href=".{% static 'dist/style.css' %}">
    <link rel="stylesheet" href="{% static 'dist/output.css' %}">
</head>
<body class="md:h-[100vh] bg-slate-100">
    <div class="flex flex-row justify-between flex-grow">
        <div>
            <div class="mb-3">
                <h2 class="font-extrabold text-3xl mt-6 mb-0 ml-7">Pick Up Where You Left Off</h2>
                <h4 class="font-extralight text-1xl ml-7">Dashboard</h4>
            </div>
            <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-3 md:grid-cols-4 md:gap-4 mx-7 mb-5">
                <div class="bg-orange-400 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">Total Contributions</h6>
                    <br>
                    <p class="font-mono">KES {{ contrib }}</p>
                </div>
                <div class="bg-lime-300 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">My Contributions</h6>
                    <br>
                    <p class="font-mono">KES {{ mine }}</p>
                </div>
                <div class="bg-emerald-400 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">Total Revenue</h6>
                    <br>
                    <p class="font-mono">KES {{ revenue }}</p>
                </div>
                <div class="bg-purple-400 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">My Total Shares</h6>
                    <br>
                    <p class="font-mono">KES {{ shares }}</p>
                </div>
                <div class="bg-cyan-700 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">Total Returns</h6>
                    <br>
                    <p class="font-mono">KES {{ returns }}</p>
                </div>
                <div class="bg-red-400 text-white border-black rounded-lg shadow-lg text-center p-8">
                    <h6 class="text-md font-bold font-['Poppins']">Pending Contributions</h6>
                    <br>
                    <p class="font-mono">KES {{ arrears }}</p>
                </div>
                <!--div class="bg-sky-300 text-white border-black rounded-lg shadow-lg text-center p-8 hover:bg-slate-50 hover:text-black hover:cursor-pointer">
                    <h6 class="text-md font-bold font-['Poppins']">Make Contribution</h6>
                    <br>
                    <p class="font-mono"><i class="box-arrow-up-right"></i>
                    </p>
                </div-->
            </div>
        </div>
        <div class="hidden md:bg-gradient-to-l md:from-[rgb(116,62,227)] md:to-[rgba(246,110,26,1)] md:block md:h-[100vh] md:pl-16 sm:pr-8">
            <div class="user-container">
                <div class="text-5xl font-['Poppins'] font-bold"><h3>Hello, {{ member.registration.first_name }}</h3></div>
            </div>
            <div class="menu-items">
                <h6>Menu</h6>
                <ul>
                    <!--li><a href="accountinfo.html">Account</a></li>
                    <li>Send Feedback</li>
                    <li>Generate Reports</li>
                    <li>Active Projects</li-->
                    <li><a href="{% url 'core:index' %}">Log Out</a></li>
                </ul>
            </div>
            <div class="textbox-bottom">
                <p>Want any help? <a href="#">Contact Us</a></p>
                <div class="copyright">
                    <p>&#169 Schcomrade Chama, 2023</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

core/templates/pending_report.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="../static/dist/output.css">
</head>
<body>
    <h1 class="text-4xl text-center">Members</h1>

    <div>
        <h2 class="text-center text-3xl font-serif my-5">Requests for Membership</h2>
    {% if person %}
    <table class="table-auto border-collapse border border-blue-500 mx-auto">
        <thead class="bg-slate-500">
            <tr>
                <th class="px-2 border border-blue-500">First Name</th>
                <th class="px-2 border border-blue-500">Second Name</th>
                <th class="px-2 border border-blue-500">Date of Birth</th>
                <th class="px-2 border border-blue-500">Phone Number</th>
                <th class="px-2 border border-blue-500">Email</th>
            </tr>
        </thead>
        {% for record in person %}
        <tr>
            <td class="border border-blue-500">{{record.first_name}}</td>
            <td class="border border-blue-500">{{record.second_name}}</td>
            <td class="border border-blue-500">{{record.date_of_birth}}</td>
            <td class="border border-blue-500">+254{{record.phone_number}}</td>
            <td class="border border-blue-500">{{record.email}}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <p>NO NEW MEMBERSHIP REQUESTS!</p>
    {% endif %}
    </div>

    <h2>APPROVED MEMBERS</h2>
    {% if members %}
        {% for member in members %}
            <p>{{member.registration.first_name}}</p>
            <p>{{member.joined_on}}</p>
        {% endfor %}
    {% else %}
        <p>NOTHING TO SEE HERE</p>
    {% endif %}
</body>
</html>

core/templates/reg-success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../static/dist/output.css">

    <title>Application Sent | Shcomrade</title>
</head>
<body>
    <<body class="h-[100vh]">
        <div class="flex my-auto h-[100vh]">
            <div class="mx-auto h-[100vh] leaves">
                <h1 class="text-5xl text-center font-sans font-bold py-36 pb-2 text-purple-900 mx-auto">Shcomrade Database Management System</h1>
                <div class="text-white font-bold text-center mt-2 px-5 py-3 rounded-md mx-52 bg-blue-700 hover:bg-blue-500">
                    <h3>Learn More</h3>
                </div>
            </div>
            <div class="login mb-auto bg-gradient-to-r from-rose-600 to-fuchsia-600 px-14 my-auto h-[100vh]">
                THANK YOU FOR YOUR INTEREST IN JOINING US
                <div class="absolute bottom-0">
                    <p>Copyright &copy; 2023 Shcomrade Chama Ltd.</p>
                </div>
            </div>
        </div>
    </body>
</body>
</html>